services:
  - type: web
    name: suspension-sim-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
